### ISSUE TITLE
Pushing packages to GPR no longer works

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#714] opened 2020-10-08 14:15 UTC
the error looks like this:

```
Executing: "C:/Tools/NuGet/NuGet.exe" sources Add -Name "PreReleaseSource_GPR" -Source "https://nuget.pkg.github.com/nils-org/index.json" -NonInteractive -UserName "nils-a" -Password "[REDACTED]"
Package source with Name: PreReleaseSource_GPR added successfully.
Pushing C:/projects/quartz-lightcore/BuildArtifacts/Packages/NuGet/Quartz.LightCore.0.1.0-alpha0038.nupkg to PreRelease Source with Url https://nuget.pkg.github.com/nils-org/index.json...
Resolved tool to path C:/Tools/NuGet/NuGet.exe
Executing: "C:/Tools/NuGet/NuGet.exe" push "C:/projects/quartz-lightcore/BuildArtifacts/Packages/NuGet/Quartz.LightCore.0.1.0-alpha0038.nupkg" "[REDACTED]" -NonInteractive -Source "https://nuget.pkg.github.com/nils-org/index.json"
Pushing Quartz.LightCore.0.1.0-alpha0038.nupkg to 'https://nuget.pkg.github.com/nils-org'...
  PUT https://nuget.pkg.github.com/nils-org/
WARNING: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
MSBuild auto-detection: using msbuild version '16.7.0.37604' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin'.
Using credentials from config. UserName: nils-a
WARNING: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
WARNING: The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
  Unauthorized https://nuget.pkg.github.com/nils-org/ 521ms
```

`GPR_USER` and `GPR_PASSWORD` are set correctly. `GPR_API_KEY` is not set.

**Comment by AdmiringWorm** [comment] 2020-10-08 14:19
known problem, and @gep13 have already fixed this but currently not released.
https://github.com/cake-contrib/Cake.Recipe/issues/706

**Comment by AdmiringWorm** [comment] 2020-10-08 14:19
Duplicate of #706

**Closed by AdmiringWorm** 2020-10-08 14:19 UTC
