### ISSUE TITLE
Reference Cake.Incubator 4.0.0

### ISSUE THREAD

**Issue by kolesnick** [cake-contrib/Cake.Recipe#364] opened 2019-05-02 10:13 UTC
`Cake.Incubator` `4.0.0` contains fix of NRE on F# project files.

**Comment by AdmiringWorm** [comment] 2019-05-02 14:09
There is already a open issue for bumping the Cake.Incubator version.
Duplicate of #324

**Closed** 2019-05-02 17:04 UTC
