### ISSUE TITLE
Something changed for RunDotNetCore artifacts output

### ISSUE THREAD

**Issue by devlead** [cake-contrib/Cake.Recipe#200] opened 2018-02-15 10:09 UTC
Previously `BuildArtifacts\temp\_PublishedLibraries\{project}` contained framework moniker for multitargeted builds
```
net46
   dll/pdb/xml/etc.
netstandard1.6
   dll/pdb/xml/etc.
```
Now we just see `dll/pdb/xml/etc.` for one framework directly in that folder with no framework monikers.

Pinned to `0.3.0-unstable0342` and now the builds work again,.

**Comment by devlead** [comment] 2018-02-15 10:26
Haven't had time to go deep bur have a hunch this is what's failing
https://github.com/cake-contrib/Cake.Recipe/blob/421bbb7853b131c985207ab486f516dafaaf4bce/Cake.Recipe/Content/build.cake#L258
and see that Cake.Incubator has been updated so could be an issue not identifying the project correctly and therefor not iterating over target frameworks

**Comment by gep13** [comment] 2018-02-15 10:46
Hmm, yes, I did update to the latest Cake.incubator.  Which project are you seeing this fail on?

**Comment by devlead** [comment] 2018-02-15 11:45
A few internal projects, but just now manually triggered builds of Cake.Kudu & Cake.Kudu.Client, and those failed after rebuild
https://ci.appveyor.com/project/cakecontrib/cake-kudu/build/0.6.0.build.10#L1051
https://ci.appveyor.com/project/cakecontrib/cake-kudu-client/build/0.1.0.build.22#L401

Builds which previously worked fine.

**Comment by gep13** [comment] 2018-02-15 12:23
@devlead ok, can't look at it just now, but I will let you know if I find out anything.

**Comment by gep13** [comment] 2018-02-15 12:24
@wwwlicious would be good to get some input here as well if you have a minute, thanks!

**Comment by wwwlicious** [comment] 2018-02-15 19:39
@devlead @gep13 
I did 'correct' the meaning of that particular flag as it wasn't technically correct from 
is this a project is vs2017 csproj format
to 
this is a netcore csproj 

Can you point me to the csproj file and I'll take a look?

**Comment by gep13** [comment] 2018-02-15 20:49
@wwwlicious one of the project files can be found here:

https://github.com/cake-contrib/Cake.Kudu/blob/master/src/Cake.Kudu/Cake.Kudu.csproj

**Comment by wwwlicious** [comment] 2018-02-15 22:26
@gep13 so based on the project file `IsNetCore` will return false.
As I understand it, it isn't a netcore project but a netstandard one. For this `IsNetStandard` can be used.

Could receipe be changed to include this?
```
// If .NET Core project, copy using dotnet publish for each target framework
// Otherwise just copy
if (parsedProject.IsNetCore || parsedProject.IsNetStandard)
{
```
Also, does `DotNetCorePublish` work for targetframeworks net4x?

**Comment by gep13** [comment] 2018-02-16 07:34
Happy to give this a try...

**Comment by gep13** [comment] 2018-02-16 07:37
@devlead new version building now. When you have a minute, can you please take it for a spin?

**Comment by devlead** [comment] 2018-02-16 09:09
Tried version `Cake.Recipe.0.3.0-unstable0356` gives me the same error. pinning to version `0.3.0-unstable0350` before addins were updated and everything works.

So correct or not, some breaking change has occurred.

**Comment by wwwlicious** [comment] 2018-02-16 09:11
@devlead Thanks, I'll do some more investigation.

**Comment by devlead** [comment] 2018-02-16 09:29
Don't know if it's a lead or not but saw these warnings in the build log
```
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(241,12): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(243,44): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(271,36): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(328,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(337,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(345,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(353,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
C:/projects/cake-kudu-client/tools/Cake.Recipe.0.3.0-unstable0354/Content/build.cake(361,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead for multi-targeting support'
```

**Comment by wwwlicious** [comment] 2018-02-16 09:38
@devlead yes the outputPath no longer makes sense. 

In pre-vs2017 format, you could only specifiy a configuration which determined the artifact output path.

In post vs2017 format, you can have 1 output path for artifacts per target targetframework and platform identifier/s so a single outputPath is no longer guaranteed. 
`OutputPaths` include all the artifact output paths and this is also reflected in `GetOutputAssembly()` which is now marked obsolete in favour of `GetOutputAssemblies()` which again respects multi-targeting.

Although I marked the properties as obsolete, it still takes the first targetframework specified (in either `<targetframework/>` or `<targetframeworks/>` to get the output paths for both so the actual behaviour should not have changed.

**Comment by wwwlicious** [comment] 2018-02-17 15:43
@gep13 @devlead So I've been doing some more digging. I copied the csproj file for Cake.Kudu into a unit test and confirmed the following outputs based on what build.cake was accessing and it all looks as I would expect. 

```csharp
var result = file.ParseProject("Release");
result.IsVS2017ProjectFormat.Should().BeTrue();
result.IsNetCore.Should().BeFalse();
result.IsNetStandard.Should().BeTrue();
result.IsNetFramework.Should().BeTrue();
result.OutputPath.FullPath.Should().Be("bin/Release/netstandard1.6");
result.OutputPaths.Should().Contain(x => x.FullPath.EqualsIgnoreCase("bin/Release/netstandard1.6"));
result.OutputPaths.Should().Contain(x => x.FullPath.EqualsIgnoreCase("bin/Release/net46"));
result.NetCore.TargetFrameworks.ShouldBeEquivalentTo(new []{ "netstandard1.6", "net46"});
result.RootNameSpace.Should().Be("Cake.Kudu");
result.IsLibrary().Should().BeTrue();
```
looking at the code in build.cake, I think the issue is that non-exe projects are not copying build outputs at all. For exe projects, the outputs are only copied 'per framework' via dotnetpublish if `IsNetCore` or `IsNetStandard` is true. Other exe projects will only copy the 'first' targetframework build artifacts.

```csharp
if(!parsedProject.IsLibrary())
{
  // If .NET Core project, copy using dotnet publish for each target framework
  // Otherwise just copy
  if(parsedProject.IsNetCore)
  {
    // iterate frameworks, call dotnetpublish
  }
  else {
    // multi-target will have 1 output path per targetframework, this only copies the 'first' framework found
    CopyFiles(GetFiles(parsedProject.OutputPath.FullPath + "/**/*"), outputFolder, true);
  }
}
// no outputs copied for library projects (of which cake.kudu is one)
```

I don't really follow this too well as I don't understand how the rest of the receipt pipeline is using those expected artifacts but I would suggest the above logic should perhaps be changed so that instead of altering publish/copy behaviour based on `IsLibrary()`, use `IsVS2017ProjectFormat` flag as this afaik allows dotnetpublish to work or not, regardless of targetframeworks.
(not sure if it is still required to iterate targetframeworks either or whether dotnetpublish does this already)

For older projects, the CopyFiles should iterate for all `OutputPaths`, not just `OutputPath` which is marked as obsolete for this reason.

**Comment by devlead** [comment] 2018-02-26 16:40
Well it used to work, more builds that fail that I need to pin to previous recipe
https://ci.appveyor.com/project/cakecontrib/cake-slack/build/0.10.1-PullRequest.21+2.build.22

**Comment by gep13** [comment] 2018-02-26 19:48
@devlead @wwwlicious can we schedule some time at some point to walk through this to make sure that we are all on the same page?  Want to make sure that nothing else has changed, outwith Cake.Incubator.

**Comment by wwwlicious** [comment] 2018-03-01 18:50
@gep13 @devlead Sure, been offline the last few days with man flu but back functioning again. Evenings (uk) would suit me best...

**Closed** 2018-03-06 21:38 UTC

**Comment by gep13** [comment] 2018-03-06 21:39
@devlead @pascalberger can one of you take the latest Cake.Recipe for a spin to see if this is now corrected?  I have it on good authority from @mholo65 that this is now corrected.

**Comment by mholo65** [comment] 2018-03-06 21:54
@gep13 verified here https://github.com/cake-contrib/Cake.Kudu/pull/10

**Comment by devlead** [comment] 2018-03-06 21:57
Can confirm it's now working Cake.Kudu.Client

**Comment by pascalberger** [comment] 2018-03-06 22:09
@gep13 Also works for me here https://github.com/cake-contrib/Cake.Issues/pull/16

**Comment by gep13** [comment] 2018-03-07 08:05
@devlead @pascalberger thank you both for confirming, and thank you @mholo65 for fixing it! 😄
