### ISSUE TITLE
tools/*.csproj are included when packing by var projects = GetFiles(BuildParameters.SourceDirectoryPath + "/**/*.csproj")

### ISSUE THREAD

**Issue by ghuntley** [cake-contrib/Cake.Recipe#210] opened 2018-04-04 06:08 UTC
The logic at https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/nuget.cake#L6-L7 

![image](https://user-images.githubusercontent.com/127353/38291267-4dd04832-3822-11e8-9ee8-7c0ba3949d42.png)

Will cause `dotnet pack` to attempt to pack any csproj that may be in `tools/*` which results in failures such as:

![image](https://user-images.githubusercontent.com/127353/38289699-e11f665c-381a-11e8-8b13-0bcc36c9bab8.png)

Related:
* https://github.com/cake-contrib/Cake.PinNuGetDependency/pull/3
* https://github.com/reactiveui/ReactiveUI/pull/1587

**Comment by gep13** [comment] 2018-04-04 07:32
@ghuntley ok, so I understand that the problem is, and why it is happening, and as a result, why I haven't seen this before.

Cake.Recipe is reasonably "strict" on the layout of the files in the repository (although normally things "just" work).  The part in question here is the usage of a `src` or `source` folder.  You can see that being used here as an example:

https://github.com/cake-contrib/Cake.Gem

The Glob pattern that you have picked up on works, because there is an assumption that you are also using a `src` or `source` folder.  Looks like you were using one in Cake.PinNuGetDependency, and you have moved away from it in the refactor to use Cake.Recipe.

The change that you are suggesting makes sense though, so let's go ahead and get it merged.

**Closed** 2018-04-04 07:33 UTC
Labels: Bug

**Comment by ghuntley** [comment] 2018-04-04 07:38
<3

**Comment by ghuntley** [comment] 2018-04-04 07:46
Okay, that makes total sense. I've bumped the source into `src/*` instead of a root folder and it's working. You don't need to do a special out-of-band release.
